### ISSUE TITLE
coerce id "0668" detects integer, returns 688;

### ISSUE THREAD

**Issue by BerkeleyTrue** [strongloop/strong-remoting#143]
Using model id's that allow for leading zero's and all number characters causes the coerce function in http-context.js [here](https://github.com/strongloop/strong-remoting/blob/67d4b139f323ce2a5e7a2e785320f66776275e92/lib/http-context.js#L188) to change model ids to integers and remove leading zeros.

This was causing a new model to be created with id 688 and model '0688' was not being updated. 

Not sure if this was intended, but I will be making sure all id's require at least one alpha character to avoid this, but wanted to have some record of this for future reference.

**Comment by ritch** [comment]
Here is what I'd like to do to fix this:

1. Take the type of the argument into account to allow explicit type coercion
2. For non-typed arguments... support intelligent coercion using @BerkeleyTrue's suggestion (leading with a 0 is a string)

I would consider 1 an enhancement and 2 a bug fix. I'll create separate issues to track these changes.

**Comment by richardpringle** [comment]
Looks like this issue has been resolved. Please re-open if there are any further problems. 

@bajtos, I know that you have the story to deal with some coercion issues in strong-remoting but I believe that this is not related. Please correct me if I am wrong.

**Comment by bajtos** [comment]
The issue is fixed in the upcoming 3.0 release.

- When the argument's type is `any`, strong-remoting will treat integer numbers starting with `0` as string, e.g. `0668` will preserve the leading zero. However, floats are still converted to numbers, e.g. both `0.42` and `00.42` are converted to a number.

- When the argument's type is `number` or `integer`, strong-remoting will treat integer numbers starting with `0` as numbers and discarding any extra leading zeroes.

**Comment by bajtos** [comment]
Actually it looks like this issue was already fixed in 2.13.0 by #168.
