### ISSUE TITLE
the `query` parameter in HttpInvocation.createRequest() is not parametrized.

### ISSUE THREAD

**Issue by simoami** [strongloop/strong-remoting#225]
In line https://github.com/strongloop/strong-remoting/blob/master/lib/http-invocation.js#L197 
the query parameter is passed in as input but have never been initialized to anything. 

It's possible that the proper initialization is:

```
var query = this.query;
```

**Comment by richardpringle** [comment]
Hey @simoami, when you click on a line like you did, please hit 'Y' on the keyboard (no ctrl or command or anything). That will reference the actual commit instead of the continuously changing branch (in this case master). 

Also, I'm not quite sure what the problem is here... I am going to close the issue for now, please re-open with the new link and a more detailed description of the problem, then mention me in a new comment. I haven't seen any issues with the current implementation.

Also, please don't feel as though I am ignoring the issue. I tend to close old issue so we can have a better picture of what is still relevant (since so many issues didn't receive any love). It's easy enough to re-open anyway :smiley:.
