### ISSUE TITLE
Required string argument should reject empty string

### ISSUE THREAD

**Issue by STRML** [strongloop/strong-remoting#263]
In practice, you're going to want to be guarding this anyway, so strong-remoting may as well do it.

Given all the sloppy http coercion, there's in practice little difference between `undefined`, `null`, and `''`. If I mark a string argument as `required`, I expect there to be an actual string there. Thoughts?

If you agree, (and also merge #260), I can form https://github.com/STRML/strong-remoting/commit/8a68689428ba8d097b631063d84a2461b8763922 into a PR.

**Comment by STRML** [comment]
Additionally, if we do go this route, I think it makes sense to fail if an array argument is empty in combination with `required`.

**Comment by richardpringle** [comment]
@bajtos (in case you haven't noticed, I'm doing a little spring cleaning on the strong-remoting backlog) what do you think about this? 

I tend to agree with @STRML but I'm not sure about our current users. This might be a good candidate for our next release since there is already a PR.

@STRML, sorry about the lack of attention, we're improving but still have a long way to go.

**Comment by bajtos** [comment]
+1 for rejecting empty string for required string args. I am not sure about rejecting empty arrays for required array args, perhaps we can add an option to control this behaviour?

I am taking a deeper look at the coercion issues in strong-remoting, let's fix this as part of that work.

**Comment by bajtos** [comment]
This should be fixed by https://github.com/strongloop/strong-remoting/pull/343 in the latest 3.0-alpha.
