### ISSUE TITLE
socket-io example doesn't work

### ISSUE THREAD

**Issue by webup** [strongloop/strong-remoting#280]
Seems the code of "client.js" is out-of-date...

``` sh
Error: Cannot find module '../../client/js/client'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
```

**Comment by webup** [comment]
After some dive into `lib/socket-io-adapter.js` and `remote-objects.js`, I found adaptor's `connect` method is not implemented for its potential invoking in `RemoteObjects.prototype.connect`, any special reason here?

**Comment by richardpringle** [comment]
Hey @webup, sorry about the delay in response time! You're right, that example is outdated. 
..and some of the socket-io adapter code is outdated as well.

Feel free to try and make the fix yourself and submit a PR. Otherwise, you'll have to be patient and wait until one of us get to this issue.

Thanks for pointing it out and happy coding!

**Comment by richardpringle** [comment]
All the info you need about the contribution process is [right here](https://github.com/strongloop/loopback/wiki/Contributing-code)

**Comment by bajtos** [comment]
I am afraid the socket.io adapter won't be a priority for us in the foreseeable future.
