### ISSUE TITLE
qs + arrays + object ids

### ISSUE THREAD

**Issue by BoLaMN** [strongloop/strong-remoting#320]
qs doesn't seem to handle object ids or arrays very well and generates a query string another loopback api server can't pass 

generated qs 

where%5Bids%5D%5Binq%5D%5B0%5D%5B_bsontype%5D=ObjectID&where%5Bids%5D%5Binq%5D%5B0%5D%5Bid%5D=W%EF%BF%BD%20%EF%BF%BD%EF%BF%BDPi%00%01%2C%EF%BF%BD6&where%5Bids%5D%5Binq%5D%5B1%5D%5B_bsontype%5D=ObjectID&where%5Bids%5D%5Binq%5D%5B1%5D%5Bid%5D=W%EF%BF%BD%20%EF%BF%BD%EF%BF%BDPi%00%01%2C%EF%BF%BD7

https://tonicdev.com/57851f8692756613004941c4/57851f8692756613004941c5

**Comment by richardpringle** [comment]
@BoLaMN can I close this in favor of #324? The description in that issue is a little more detailed. If you would like, you can take the description of this issue and place it as a comment in the other.

If you have any objections, please re-open the issue and mention me in a comment and I will tend to it right away.
