### ISSUE TITLE
Returns fail with SharedMethod

### ISSUE THREAD

**Issue by kimkha** [strongloop/strong-remoting#407]
Look at this function [SharedMethod.toResult](https://github.com/strongloop/strong-remoting/blob/master/lib/shared-method.js#L473). It fail if we want it return many infos.

For example:

```
returns = [
        {
          "arg": "data",
          "type": [
            "string"
          ],
          "root": true
        },
        {
          "arg": "X-Total-Count",
          "type": "number",
          "http": {
            "target": "header"
          }
        }
      ]
```

```
raw = [
      [ "test" ],
      1
    ]
```

Then, after `returns = returns.filter(...)`, the "data" was removed. And after that, line `returns.forEach(...)` did not include the "data", just only one element "X-Total-Count".

So, when it fetch value of `raw[index]`, the "index" is 0 in `returns`, but its index is 1 in `raw`.

Thanks

**Comment by bajtos** [comment]
@kimkha thank you for reporting the problem. Could you please provide us with full steps for reproducing it? For example, a failing unit-test that can be added to strong-remoting's test suite, or a small application per our [Bug reporting instructions](http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report).

**Comment by mitsos1os** [comment]
The reported issue is valid. The problem is that when the remote method returns a Promise, the return arguments specified in the remote method that have a `http.target` option set to `status` or `header` are not processed correctly. This is not happening when the remote method uses the callback provided

The reason this is hapenning is that when promise mode is used the context is not passed as argument [here](https://github.com/strongloop/strong-remoting/blob/bf3b2cefe4705ccc2384c02ecc9d8cda5d5dd724/lib/shared-method.js#L275) as opposed to [Callback mode](https://github.com/strongloop/strong-remoting/blob/bf3b2cefe4705ccc2384c02ecc9d8cda5d5dd724/lib/shared-method.js#L256), so later the check in [toResult](https://github.com/strongloop/strong-remoting/blob/bf3b2cefe4705ccc2384c02ecc9d8cda5d5dd724/lib/shared-method.js#L485) fails to process them correctly

**Comment by bajtos** [comment]
> The reason this is hapenning is that when promise mode is used the context is not passed as argument here as opposed to Callback mode, so later the check in toResult fails to process them correctly

Thank you @mitsos1os for investigating the issue and finding the place where to fix it.

Would you like to contribute the fix yourself and submit a pull request?

**Comment by mitsos1os** [comment]
Yes I will thank you
